/**
 * guestData.ts
 * Handles data for playing as a guest.
 * @version 2026.02.11
 */
export interface GuestTrack {
    track: {
        id: string;
        name: string;
        artists: { name: string }[];
        album: {
            name: string;
            images: { url: string }[];
        };
    };
    is_local?: boolean;
}

export const GUEST_PLAYLISTS = [
    {
        id: 'guest_top_hits',
        name: 'Top Hits',
        images: [{ url: 'https://charts-images.scdn.co/assets/locale_en/regional/weekly/region_global_default.jpg' }],
        tracks: { total: 50 }
    },
    {
        id: 'guest_rock_classics',
        name: 'Rock Classics',
        images: [{ url: 'https://i.scdn.co/image/ab67706f00000003ae5a452a3d0edcf819129532' }],
        tracks: { total: 50 }
    },
    {
        id: 'guest_indie_classics',
        name: 'Indie Classics',
        images: [{ url: 'https://i.scdn.co/image/ab67706f0000000355aa2d2d0b0467c6999b1d1f' }],
        tracks: { total: 50 }
    },
    {
        id: 'guest_hip_hop',
        name: 'Hip Hop & Rap',
        images: [{ url: 'https://i.scdn.co/image/ab67706f000000039249b35f23fb696b4b2e5917' }],
        tracks: { total: 50 }
    }
];

export const GUEST_TRACKS: Record<string, GuestTrack[]> = {
    'guest_top_hits': [
        { track: { id: 'gh1', name: 'As It Was', artists: [{ name: 'Harry Styles' }], album: { name: 'Harry\'s House', images: [] } } },
        { track: { id: 'gh2', name: 'Anti-Hero', artists: [{ name: 'Taylor Swift' }], album: { name: 'Midnights', images: [] } } },
        { track: { id: 'gh3', name: 'Flowers', artists: [{ name: 'Miley Cyrus' }], album: { name: 'Endless Summer Vacation', images: [] } } },
        { track: { id: 'gh4', name: 'Kill Bill', artists: [{ name: 'SZA' }], album: { name: 'SOS', images: [] } } },
        { track: { id: 'gh5', name: 'Creepin\'', artists: [{ name: 'Metro Boomin, The Weeknd, 21 Savage' }], album: { name: 'HEROES & VILLAINS', images: [] } } },
        { track: { id: 'gh6', name: 'Cruel Summer', artists: [{ name: 'Taylor Swift' }], album: { name: 'Lover', images: [] } } },
        { track: { id: 'gh7', name: 'Vampire', artists: [{ name: 'Olivia Rodrigo' }], album: { name: 'GUTS', images: [] } } },
        { track: { id: 'gh8', name: 'Calm Down', artists: [{ name: 'Rema & Selena Gomez' }], album: { name: 'Rave & Roses Ultra', images: [] } } },
        { track: { id: 'gh9', name: 'Last Night', artists: [{ name: 'Morgan Wallen' }], album: { name: 'One Thing At A Time', images: [] } } },
        { track: { id: 'gh10', name: 'Dance The Night', artists: [{ name: 'Dua Lipa' }], album: { name: 'Barbie The Album', images: [] } } },
        { track: { id: 'gh11', name: 'Seven (feat. Latto)', artists: [{ name: 'Jung Kook' }], album: { name: 'GOLDEN', images: [] } } },
        { track: { id: 'gh12', name: 'vampire', artists: [{ name: 'Olivia Rodrigo' }], album: { name: 'GUTS', images: [] } } },
        { track: { id: 'gh13', name: 'Paint The Town Red', artists: [{ name: 'Doja Cat' }], album: { name: 'Scarlet', images: [] } } },
        { track: { id: 'gh14', name: 'Sprinter', artists: [{ name: 'Dave & Central Cee' }], album: { name: 'Split Decision', images: [] } } },
        { track: { id: 'gh15', name: 'Fast Car', artists: [{ name: 'Luke Combs' }], album: { name: 'Gettin\' Old', images: [] } } },
        { track: { id: 'gh16', name: 'Daylight', artists: [{ name: 'David Kushner' }], album: { name: 'Daylight', images: [] } } },
        { track: { id: 'gh17', name: 'Ella Baila Sola', artists: [{ name: 'Eslabon Armado X Peso Pluma' }], album: { name: 'DESVELADO', images: [] } } },
        { track: { id: 'gh18', name: 'fukumean', artists: [{ name: 'Gunna' }], album: { name: 'a Gift & a Curse', images: [] } } },
        { track: { id: 'gh19', name: 'Cupid - Twin Ver.', artists: [{ name: 'FIFTY FIFTY' }], album: { name: 'The Beginning: Cupid', images: [] } } },
        { track: { id: 'gh20', name: 'Die For You', artists: [{ name: 'The Weeknd' }], album: { name: 'Starboy', images: [] } } },
        { track: { id: 'gh21', name: 'Boy\'s a liar Pt. 2', artists: [{ name: 'PinkPantheress & Ice Spice' }], album: { name: 'Boy\'s a liar Pt. 2', images: [] } } },
        { track: { id: 'gh22', name: 'I Ain\'t Worried', artists: [{ name: 'OneRepublic' }], album: { name: 'Top Gun: Maverick (Music From The Motion Picture)', images: [] } } },
        { track: { id: 'gh23', name: 'Unholy', artists: [{ name: 'Sam Smith & Kim Petras' }], album: { name: 'Gloria', images: [] } } },
        { track: { id: 'gh24', name: 'Rich Flex', artists: [{ name: 'Drake & 21 Savage' }], album: { name: 'Her Loss', images: [] } } },
        { track: { id: 'gh25', name: 'LAVENDER HAZE', artists: [{ name: 'Taylor Swift' }], album: { name: 'Midnights', images: [] } } },
        { track: { id: 'gh26', name: 'Starboy', artists: [{ name: 'The Weeknd' }], album: { name: 'Starboy', images: [] } } },
        { track: { id: 'gh27', name: 'Mockingbird', artists: [{ name: 'Eminem' }], album: { name: 'Encore', images: [] } } },
        { track: { id: 'gh28', name: 'Blinding Lights', artists: [{ name: 'The Weeknd' }], album: { name: 'After Hours', images: [] } } },
        { track: { id: 'gh29', name: 'Stay', artists: [{ name: 'The Kid LAROI & Justin Bieber' }], album: { name: 'F*CK LOVE 3: OVER YOU', images: [] } } },
        { track: { id: 'gh30', name: 'Heat Waves', artists: [{ name: 'Glass Animals' }], album: { name: 'Dreamland', images: [] } } },
        { track: { id: 'gh31', name: 'Perfect', artists: [{ name: 'Ed Sheeran' }], album: { name: '÷ (Divide)', images: [] } } },
        { track: { id: 'gh32', name: 'Shape of You', artists: [{ name: 'Ed Sheeran' }], album: { name: '÷ (Divide)', images: [] } } },
        { track: { id: 'gh33', name: 'Believer', artists: [{ name: 'Imagine Dragons' }], album: { name: 'Evolve', images: [] } } },
        { track: { id: 'gh34', name: 'Sunflower', artists: [{ name: 'Post Malone & Swae Lee' }], album: { name: 'Spider-Man: Into the Spider-Verse', images: [] } } },
        { track: { id: 'gh35', name: 'One Dance', artists: [{ name: 'Drake' }], album: { name: 'Views', images: [] } } },
        { track: { id: 'gh36', name: 'Closer', artists: [{ name: 'The Chainsmokers' }], album: { name: 'Collage', images: [] } } },
        { track: { id: 'gh37', name: 'Someone You Loved', artists: [{ name: 'Lewis Capaldi' }], album: { name: 'Divinely Uninspired To A Hellish Extent', images: [] } } },
        { track: { id: 'gh38', name: 'Sweater Weather', artists: [{ name: 'The Neighbourhood' }], album: { name: 'I Love You.', images: [] } } },
        { track: { id: 'gh39', name: 'Another Love', artists: [{ name: 'Tom Odell' }], album: { name: 'Long Way Down', images: [] } } },
        { track: { id: 'gh40', name: 'Riptide', artists: [{ name: 'Vance Joy' }], album: { name: 'Dream Your Life Away', images: [] } } },
        { track: { id: 'gh41', name: 'Take Me To Church', artists: [{ name: 'Hozier' }], album: { name: 'Hozier', images: [] } } },
        { track: { id: 'gh42', name: 'Counting Stars', artists: [{ name: 'OneRepublic' }], album: { name: 'Native', images: [] } } },
        { track: { id: 'gh43', name: 'Can\'t Hold Us', artists: [{ name: 'Macklemore & Ryan Lewis' }], album: { name: 'The Heist', images: [] } } },
        { track: { id: 'gh44', name: 'Wake Me Up', artists: [{ name: 'Avicii' }], album: { name: 'True', images: [] } } },
        { track: { id: 'gh45', name: 'Demons', artists: [{ name: 'Imagine Dragons' }], album: { name: 'Night Visions', images: [] } } },
        { track: { id: 'gh46', name: 'Rolling in the Deep', artists: [{ name: 'Adele' }], album: { name: '21', images: [] } } },
        { track: { id: 'gh47', name: 'Viva La Vida', artists: [{ name: 'Coldplay' }], album: { name: 'Viva La Vida or Death and All His Friends', images: [] } } },
        { track: { id: 'gh48', name: 'Pompeii', artists: [{ name: 'Bastille' }], album: { name: 'Bad Blood', images: [] } } },
        { track: { id: 'gh49', name: 'Ho Hey', artists: [{ name: 'The Lumineers' }], album: { name: 'The Lumineers', images: [] } } },
        { track: { id: 'gh50', name: 'Royals', artists: [{ name: 'Lorde' }], album: { name: 'Pure Heroine', images: [] } } },
    ],
    'guest_rock_classics': [
        { track: { id: 'gr1', name: 'Bohemian Rhapsody', artists: [{ name: 'Queen' }], album: { name: 'A Night at the Opera', images: [] } } },
        { track: { id: 'gr2', name: 'Hotel California', artists: [{ name: 'Eagles' }], album: { name: 'Hotel California', images: [] } } },
        { track: { id: 'gr3', name: 'Sweet Child O\' Mine', artists: [{ name: 'Guns N\' Roses' }], album: { name: 'Appetite for Destruction', images: [] } } },
        { track: { id: 'gr4', name: 'Back In Black', artists: [{ name: 'AC/DC' }], album: { name: 'Back in Black', images: [] } } },
        { track: { id: 'gr5', name: 'Don\'t Stop Believin\'', artists: [{ name: 'Journey' }], album: { name: 'Escape', images: [] } } },
        { track: { id: 'gr6', name: 'Smells Like Teen Spirit', artists: [{ name: 'Nirvana' }], album: { name: 'Nevermind', images: [] } } },
        { track: { id: 'gr7', name: 'Sweet Home Alabama', artists: [{ name: 'Lynyrd Skynyrd' }], album: { name: 'Second Helping', images: [] } } },
        { track: { id: 'gr8', name: 'Fortunate Son', artists: [{ name: 'Creedence Clearwater Revival' }], album: { name: 'Willy and the Poor Boys', images: [] } } },
        { track: { id: 'gr9', name: 'Livin\' On A Prayer', artists: [{ name: 'Bon Jovi' }], album: { name: 'Slippery When Wet', images: [] } } },
        { track: { id: 'gr10', name: 'Dream On', artists: [{ name: 'Aerosmith' }], album: { name: 'Aerosmith', images: [] } } },
        { track: { id: 'gr11', name: 'Light My Fire', artists: [{ name: 'The Doors' }], album: { name: 'The Doors', images: [] } } },
        { track: { id: 'gr12', name: 'Paint It, Black', artists: [{ name: 'The Rolling Stones' }], album: { name: 'Aftermath', images: [] } } },
        { track: { id: 'gr13', name: 'Baba O\'Riley', artists: [{ name: 'The Who' }], album: { name: 'Who\'s Next', images: [] } } },
        { track: { id: 'gr14', name: 'Kashmir', artists: [{ name: 'Led Zeppelin' }], album: { name: 'Physical Graffiti', images: [] } } },
        { track: { id: 'gr15', name: 'Whole Lotta Love', artists: [{ name: 'Led Zeppelin' }], album: { name: 'Led Zeppelin II', images: [] } } },
        { track: { id: 'gr16', name: 'You Shook Me All Night Long', artists: [{ name: 'AC/DC' }], album: { name: 'Back in Black', images: [] } } },
        { track: { id: 'gr17', name: 'The Joker', artists: [{ name: 'Steve Miller Band' }], album: { name: 'The Joker', images: [] } } },
        { track: { id: 'gr18', name: 'Born to Run', artists: [{ name: 'Bruce Springsteen' }], album: { name: 'Born to Run', images: [] } } },
        { track: { id: 'gr19', name: 'Free Bird', artists: [{ name: 'Lynyrd Skynyrd' }], album: { name: '(Pronounced \'Lĕh-\'nérd \'Skin-\'nérd)', images: [] } } },
        { track: { id: 'gr20', name: 'Born to Be Wild', artists: [{ name: 'Steppenwolf' }], album: { name: 'Steppenwolf', images: [] } } },
        { track: { id: 'gr21', name: 'Dream Police', artists: [{ name: 'Cheap Trick' }], album: { name: 'Dream Police', images: [] } } },
        { track: { id: 'gr22', name: 'Gimme Shelter', artists: [{ name: 'The Rolling Stones' }], album: { name: 'Let It Bleed', images: [] } } },
        { track: { id: 'gr23', name: 'All Along the Watchtower', artists: [{ name: 'The Jimi Hendrix Experience' }], album: { name: 'Electric Ladyland', images: [] } } },
        { track: { id: 'gr24', name: 'Pride and Joy', artists: [{ name: 'Stevie Ray Vaughan' }], album: { name: 'Texas Flood', images: [] } } },
        { track: { id: 'gr25', name: 'Carry On Wayward Son', artists: [{ name: 'Kansas' }], album: { name: 'Leftoverture', images: [] } } },
        { track: { id: 'gr26', name: 'La Grange', artists: [{ name: 'ZZ Top' }], album: { name: 'Tres Hombres', images: [] } } },
        { track: { id: 'gr27', name: 'Sharp Dressed Man', artists: [{ name: 'ZZ Top' }], album: { name: 'Eliminator', images: [] } } },
        { track: { id: 'gr28', name: 'Go Your Own Way', artists: [{ name: 'Fleetwood Mac' }], album: { name: 'Rumours', images: [] } } },
        { track: { id: 'gr29', name: 'The Boys Are Back In Town', artists: [{ name: 'Thin Lizzy' }], album: { name: 'Jailbreak', images: [] } } },
        { track: { id: 'gr30', name: 'Roxanne', artists: [{ name: 'The Police' }], album: { name: 'Outlandos d\'Amour', images: [] } } },
        { track: { id: 'gr31', name: 'Purple Haze', artists: [{ name: 'The Jimi Hendrix Experience' }], album: { name: 'Are You Experienced', images: [] } } },
        { track: { id: 'gr32', name: 'Jump', artists: [{ name: 'Van Halen' }], album: { name: '1984', images: [] } } },
        { track: { id: 'gr33', name: 'Simple Man', artists: [{ name: 'Lynyrd Skynyrd' }], album: { name: '(Pronounced \'Lĕh-\'nérd \'Skin-\'nérd)', images: [] } } },
        { track: { id: 'gr34', name: 'Detroit Rock City', artists: [{ name: 'KISS' }], album: { name: 'Destroyer', images: [] } } },
        { track: { id: 'gr35', name: 'Thunder Road', artists: [{ name: 'Bruce Springsteen' }], album: { name: 'Born to Run', images: [] } } },
        { track: { id: 'gr36', name: 'Start Me Up', artists: [{ name: 'The Rolling Stones' }], album: { name: 'Tattoo You', images: [] } } },
        { track: { id: 'gr37', name: 'Life in the Fast Lane', artists: [{ name: 'Eagles' }], album: { name: 'Hotel California', images: [] } } },
        { track: { id: 'gr38', name: 'Paranoid', artists: [{ name: 'Black Sabbath' }], album: { name: 'Paranoid', images: [] } } },
        { track: { id: 'gr39', name: 'You Really Got Me', artists: [{ name: 'The Kinks' }], album: { name: 'Kinks', images: [] } } },
        { track: { id: 'gr40', name: 'We Will Rock You', artists: [{ name: 'Queen' }], album: { name: 'News of the World', images: [] } } },
        { track: { id: 'gr41', name: 'Barracuda', artists: [{ name: 'Heart' }], album: { name: 'Little Queen', images: [] } } },
        { track: { id: 'gr42', name: 'Walk This Way', artists: [{ name: 'Aerosmith' }], album: { name: 'Toys in the Attic', images: [] } } },
        { track: { id: 'gr43', name: 'Smoke on the Water', artists: [{ name: 'Deep Purple' }], album: { name: 'Machine Head', images: [] } } },
        { track: { id: 'gr44', name: 'More Than a Feeling', artists: [{ name: 'Boston' }], album: { name: 'Boston', images: [] } } },
        { track: { id: 'gr45', name: 'Highway to Hell', artists: [{ name: 'AC/DC' }], album: { name: 'Highway to Hell', images: [] } } },
        { track: { id: 'gr46', name: 'Everlong', artists: [{ name: 'Foo Fighters' }], album: { name: 'The Colour and the Shape', images: [] } } },
        { track: { id: 'gr47', name: 'Welcome to the Jungle', artists: [{ name: 'Guns N\' Roses' }], album: { name: 'Appetite for Destruction', images: [] } } },
        { track: { id: 'gr48', name: 'Another One Bites the Dust', artists: [{ name: 'Queen' }], album: { name: 'The Game', images: [] } } },
        { track: { id: 'gr49', name: 'Wanted Dead or Alive', artists: [{ name: 'Bon Jovi' }], album: { name: 'Slippery When Wet', images: [] } } },
        { track: { id: 'gr50', name: 'Take It Easy', artists: [{ name: 'Eagles' }], album: { name: 'Eagles', images: [] } } }
    ],
    'guest_indie_classics': [
        { track: { id: 'gi1', name: 'Mr. Brightside', artists: [{ name: 'The Killers' }], album: { name: 'Hot Fuss', images: [] } } },
        { track: { id: 'gi2', name: 'Do I Wanna Know?', artists: [{ name: 'Arctic Monkeys' }], album: { name: 'AM', images: [] } } },
        { track: { id: 'gi3', name: 'Pumped Up Kicks', artists: [{ name: 'Foster The People' }], album: { name: 'Torches', images: [] } } },
        { track: { id: 'gi4', name: 'Sweater Weather', artists: [{ name: 'The Neighbourhood' }], album: { name: 'I Love You.', images: [] } } },
        { track: { id: 'gi5', name: 'Tongue Tied', artists: [{ name: 'Grouplove' }], album: { name: 'Never Trust a Happy Song', images: [] } } },
        { track: { id: 'gi6', name: 'Kids', artists: [{ name: 'MGMT' }], album: { name: 'Oracular Spectacular', images: [] } } },
        { track: { id: 'gi7', name: 'Electric Feel', artists: [{ name: 'MGMT' }], album: { name: 'Oracular Spectacular', images: [] } } },
        { track: { id: 'gi8', name: 'Seven Nation Army', artists: [{ name: 'The White Stripes' }], album: { name: 'Elephant', images: [] } } },
        { track: { id: 'gi9', name: 'Midnight City', artists: [{ name: 'M83' }], album: { name: 'Hurry Up, We\'re Dreaming', images: [] } } },
        { track: { id: 'gi10', name: 'Fluorescent Adolescent', artists: [{ name: 'Arctic Monkeys' }], album: { name: 'Favourite Worst Nightmare', images: [] } } },
        { track: { id: 'gi11', name: 'Dog Days Are Over', artists: [{ name: 'Florence + The Machine' }], album: { name: 'Lungs', images: [] } } },
        { track: { id: 'gi12', name: 'Somebody Told Me', artists: [{ name: 'The Killers' }], album: { name: 'Hot Fuss', images: [] } } },
        { track: { id: 'gi13', name: 'Take Me Out', artists: [{ name: 'Franz Ferdinand' }], album: { name: 'Franz Ferdinand', images: [] } } },
        { track: { id: 'gi14', name: 'Little Talks', artists: [{ name: 'Of Monsters and Men' }], album: { name: 'My Head Is an Animal', images: [] } } },
        { track: { id: 'gi15', name: 'Riptide', artists: [{ name: 'Vance Joy' }], album: { name: 'Dream Your Life Away', images: [] } } },
        { track: { id: 'gi16', name: 'Breezeblocks', artists: [{ name: 'alt-J' }], album: { name: 'An Awesome Wave', images: [] } } },
        { track: { id: 'gi17', name: 'Cigarette Daydreams', artists: [{ name: 'Cage The Elephant' }], album: { name: 'Melophobia', images: [] } } },
        { track: { id: 'gi18', name: 'Young Folks', artists: [{ name: 'Peter Bjorn and John' }], album: { name: 'Writer\'s Block', images: [] } } },
        { track: { id: 'gi19', name: 'Home', artists: [{ name: 'Edward Sharpe & The Magnetic Zeros' }], album: { name: 'Up From Below', images: [] } } },
        { track: { id: 'gi20', name: 'Ophelia', artists: [{ name: 'The Lumineers' }], album: { name: 'Cleopatra', images: [] } } },
        { track: { id: 'gi21', name: 'My Type', artists: [{ name: 'Saint Motel' }], album: { name: 'My Type', images: [] } } },
        { track: { id: 'gi22', name: 'Feel It Still', artists: [{ name: 'Portugal. The Man' }], album: { name: 'Woodstock', images: [] } } },
        { track: { id: 'gi23', name: 'Shut Up and Dance', artists: [{ name: 'WALK THE MOON' }], album: { name: 'TALKING IS HARD', images: [] } } },
        { track: { id: 'gi24', name: 'Sail', artists: [{ name: 'AWOLNATION' }], album: { name: 'Megalithic Symphony', images: [] } } },
        { track: { id: 'gi25', name: 'Renegades', artists: [{ name: 'X Ambassadors' }], album: { name: 'VHS', images: [] } } },
        { track: { id: 'gi26', name: 'Stolen Dance', artists: [{ name: 'Milky Chance' }], album: { name: 'Sadnecessary', images: [] } } },
        { track: { id: 'gi27', name: 'Safe And Sound', artists: [{ name: 'Capital Cities' }], album: { name: 'In A Tidal Wave of Mystery', images: [] } } },
        { track: { id: 'gi28', name: 'Way Down We Go', artists: [{ name: 'Kaleo' }], album: { name: 'A/B', images: [] } } },
        { track: { id: 'gi29', name: 'Mountain Sound', artists: [{ name: 'Of Monsters and Men' }], album: { name: 'My Head Is an Animal', images: [] } } },
        { track: { id: 'gi30', name: 'Ho Hey', artists: [{ name: 'The Lumineers' }], album: { name: 'The Lumineers', images: [] } } },
        { track: { id: 'gi31', name: 'Wait', artists: [{ name: 'M83' }], album: { name: 'Hurry Up, We\'re Dreaming', images: [] } } },
        { track: { id: 'gi32', name: 'First Day Of My Life', artists: [{ name: 'Bright Eyes' }], album: { name: 'I\'m Wide Awake, It\'s Morning', images: [] } } },
        { track: { id: 'gi33', name: 'Diane Young', artists: [{ name: 'Vampire Weekend' }], album: { name: 'Modern Vampires of the City', images: [] } } },
        { track: { id: 'gi34', name: 'Introduction to the Album', artists: [{ name: 'The Hotelier' }], album: { name: 'Home, Like Noplace Is There', images: [] } } },
        { track: { id: 'gi35', name: 'Wait', artists: [{ name: 'NoMBe' }], album: { name: 'They Might\'ve Even Loved Me', images: [] } } },
        { track: { id: 'gi36', name: 'Skinny Love', artists: [{ name: 'Bon Iver' }], album: { name: 'For Emma, Forever Ago', images: [] } } },
        { track: { id: 'gi37', name: 'Sprawl II (Mountains Beyond Mountains)', artists: [{ name: 'Arcade Fire' }], album: { name: 'The Suburbs', images: [] } } },
        { track: { id: 'gi38', name: 'Float On', artists: [{ name: 'Modest Mouse' }], album: { name: 'Good News for People Who Love Bad News', images: [] } } },
        { track: { id: 'gi39', name: 'Oxford Comma', artists: [{ name: 'Vampire Weekend' }], album: { name: 'Vampire Weekend', images: [] } } },
        { track: { id: 'gi40', name: 'Rebellion (Lies)', artists: [{ name: 'Arcade Fire' }], album: { name: 'Funeral', images: [] } } },
        { track: { id: 'gi41', name: 'New Slang', artists: [{ name: 'The Shins' }], album: { name: 'Oh, Inverted World', images: [] } } },
        { track: { id: 'gi42', name: 'Last Nite', artists: [{ name: 'The Strokes' }], album: { name: 'Is This It', images: [] } } },
        { track: { id: 'gi43', name: 'Someday', artists: [{ name: 'The Strokes' }], album: { name: 'Is This It', images: [] } } },
        { track: { id: 'gi44', name: '1901', artists: [{ name: 'Phoenix' }], album: { name: 'Wolfgang Amadeus Phoenix', images: [] } } },
        { track: { id: 'gi45', name: 'Lisztomania', artists: [{ name: 'Phoenix' }], album: { name: 'Wolfgang Amadeus Phoenix', images: [] } } },
        { track: { id: 'gi46', name: 'Maps', artists: [{ name: 'Yeah Yeah Yeahs' }], album: { name: 'Fever to Tell', images: [] } } },
        { track: { id: 'gi47', name: 'Wake Up', artists: [{ name: 'Arcade Fire' }], album: { name: 'Funeral', images: [] } } },
        { track: { id: 'gi48', name: 'Banquet', artists: [{ name: 'Bloc Party' }], album: { name: 'Silent Alarm', images: [] } } },
        { track: { id: 'gi49', name: 'Helicopter', artists: [{ name: 'Bloc Party' }], album: { name: 'Silent Alarm', images: [] } } },
        { track: { id: 'gi50', name: 'Naive', artists: [{ name: 'The Kooks' }], album: { name: 'Inside In / Inside Out', images: [] } } }
    ],
    'guest_hip_hop': [
        { track: { id: 'ghh1', name: 'Lose Yourself', artists: [{ name: 'Eminem' }], album: { name: '8 Mile', images: [] } } },
        { track: { id: 'ghh2', name: 'HUMBLE.', artists: [{ name: 'Kendrick Lamar' }], album: { name: 'DAMN.', images: [] } } },
        { track: { id: 'ghh3', name: 'God\'s Plan', artists: [{ name: 'Drake' }], album: { name: 'Scorpion', images: [] } } },
        { track: { id: 'ghh4', name: 'SICKO MODE', artists: [{ name: 'Travis Scott' }], album: { name: 'ASTROWORLD', images: [] } } },
        { track: { id: 'ghh5', name: 'Stronger', artists: [{ name: 'Kanye West' }], album: { name: 'Graduation', images: [] } } },
        { track: { id: 'ghh6', name: 'In Da Club', artists: [{ name: '50 Cent' }], album: { name: 'Get Rich or Die Tryin\'', images: [] } } },
        { track: { id: 'ghh7', name: 'Juicy', artists: [{ name: 'The Notorious B.I.G.' }], album: { name: 'Ready to Die', images: [] } } },
        { track: { id: 'ghh8', name: 'California Love', artists: [{ name: '2Pac' }], album: { name: 'All Eyez On Me', images: [] } } },
        { track: { id: 'ghh9', name: 'Ms. Jackson', artists: [{ name: 'Outkast' }], album: { name: 'Stankonia', images: [] } } },
        { track: { id: 'ghh10', name: 'Gold Digger', artists: [{ name: 'Kanye West' }], album: { name: 'Late Registration', images: [] } } },
        { track: { id: 'ghh11', name: 'Empire State Of Mind', artists: [{ name: 'JAY-Z' }], album: { name: 'The Blueprint 3', images: [] } } },
        { track: { id: 'ghh12', name: 'N.Y. State of Mind', artists: [{ name: 'Nas' }], album: { name: 'Illmatic', images: [] } } },
        { track: { id: 'ghh13', name: 'Hypnotize', artists: [{ name: 'The Notorious B.I.G.' }], album: { name: 'Life After Death', images: [] } } },
        { track: { id: 'ghh14', name: 'Still D.R.E.', artists: [{ name: 'Dr. Dre' }], album: { name: '2001', images: [] } } },
        { track: { id: 'ghh15', name: 'The Real Slim Shady', artists: [{ name: 'Eminem' }], album: { name: 'The Marshall Mathers LP', images: [] } } },
        { track: { id: 'ghh16', name: 'Hotline Bling', artists: [{ name: 'Drake' }], album: { name: 'Views', images: [] } } },
        { track: { id: 'ghh17', name: 'Money Trees', artists: [{ name: 'Kendrick Lamar' }], album: { name: 'good kid, m.A.A.d city', images: [] } } },
        { track: { id: 'ghh18', name: 'No Role Modelz', artists: [{ name: 'J. Cole' }], album: { name: '2014 Forest Hills Drive', images: [] } } },
        { track: { id: 'ghh19', name: 'Goosebumps', artists: [{ name: 'Travis Scott' }], album: { name: 'Birds in the Trap Sing McKnight', images: [] } } },
        { track: { id: 'ghh20', name: 'Lucid Dreams', artists: [{ name: 'Juice WRLD' }], album: { name: 'Goodbye & Good Riddance', images: [] } } },
        { track: { id: 'ghh21', name: 'XO Tour Llif3', artists: [{ name: 'Lil Uzi Vert' }], album: { name: 'Luv Is Rage 2', images: [] } } },
        { track: { id: 'ghh22', name: 'Congratulations', artists: [{ name: 'Post Malone' }], album: { name: 'Stoney', images: [] } } },
        { track: { id: 'ghh23', name: 'Bodak Yellow', artists: [{ name: 'Cardi B' }], album: { name: 'Invasion of Privacy', images: [] } } },
        { track: { id: 'ghh24', name: 'Truth Hurts', artists: [{ name: 'Lizzo' }], album: { name: 'Cuz I Love You', images: [] } } },
        { track: { id: 'ghh25', name: 'Old Town Road', artists: [{ name: 'Lil Nas X' }], album: { name: '7 EP', images: [] } } },
        { track: { id: 'ghh26', name: 'Gangsta\'s Paradise', artists: [{ name: 'Coolio' }], album: { name: 'Dangerous Minds', images: [] } } },
        { track: { id: 'ghh27', name: 'Ridin\'', artists: [{ name: 'Chamillionaire' }], album: { name: 'The Sound of Revenge', images: [] } } },
        { track: { id: 'ghh28', name: 'Crank That (Soulja Boy)', artists: [{ name: 'Soulja Boy Tell \'Em' }], album: { name: 'Souljaboytellem.com', images: [] } } },
        { track: { id: 'ghh29', name: 'Low', artists: [{ name: 'Flo Rida' }], album: { name: 'Mail on Sunday', images: [] } } },
        { track: { id: 'ghh30', name: 'Love The Way You Lie', artists: [{ name: 'Eminem' }], album: { name: 'Recovery', images: [] } } },
        { track: { id: 'ghh31', name: 'Swimming Pools (Drank)', artists: [{ name: 'Kendrick Lamar' }], album: { name: 'good kid, m.A.A.d city', images: [] } } },
        { track: { id: 'ghh32', name: 'Black Skinhead', artists: [{ name: 'Kanye West' }], album: { name: 'Yeezus', images: [] } } },
        { track: { id: 'ghh33', name: 'Power', artists: [{ name: 'Kanye West' }], album: { name: 'My Beautiful Dark Twisted Fantasy', images: [] } } },
        { track: { id: 'ghh34', name: 'Gin and Juice', artists: [{ name: 'Snoop Dogg' }], album: { name: 'Doggystyle', images: [] } } },
        { track: { id: 'ghh35', name: 'Alright', artists: [{ name: 'Kendrick Lamar' }], album: { name: 'To Pimp a Butterfly', images: [] } } },
        { track: { id: 'ghh36', name: 'm.A.A.d city', artists: [{ name: 'Kendrick Lamar' }], album: { name: 'good kid, m.A.A.d city', images: [] } } },
        { track: { id: 'ghh37', name: 'Wet Dreamz', artists: [{ name: 'J. Cole' }], album: { name: '2014 Forest Hills Drive', images: [] } } },
        { track: { id: 'ghh38', name: 'Middle Child', artists: [{ name: 'J. Cole' }], album: { name: 'Middle Child', images: [] } } },
        { track: { id: 'ghh39', name: 'Godzilla', artists: [{ name: 'Eminem' }], album: { name: 'Music To Be Murdered By', images: [] } } },
        { track: { id: 'ghh40', name: 'Without Me', artists: [{ name: 'Eminem' }], album: { name: 'The Eminem Show', images: [] } } },
        { track: { id: 'ghh41', name: 'Mockingbird', artists: [{ name: 'Eminem' }], album: { name: 'Encore', images: [] } } },
        { track: { id: 'ghh42', name: 'Not Afraid', artists: [{ name: 'Eminem' }], album: { name: 'Recovery', images: [] } } },
        { track: { id: 'ghh43', name: 'Rap God', artists: [{ name: 'Eminem' }], album: { name: 'The Marshall Mathers LP2', images: [] } } },
        { track: { id: 'ghh44', name: 'Forever', artists: [{ name: 'Drake' }], album: { name: 'Relapse: Refill', images: [] } } },
        { track: { id: 'ghh45', name: 'Started From the Bottom', artists: [{ name: 'Drake' }], album: { name: 'Nothing Was the Same', images: [] } } },
        { track: { id: 'ghh46', name: 'Nice For What', artists: [{ name: 'Drake' }], album: { name: 'Scorpion', images: [] } } },
        { track: { id: 'ghh47', name: 'Mask Off', artists: [{ name: 'Future' }], album: { name: 'FUTURE', images: [] } } },
        { track: { id: 'ghh48', name: 'X', artists: [{ name: '21 Savage & Metro Boomin' }], album: { name: 'Savage Mode II', images: [] } } },
        { track: { id: 'ghh49', name: 'Bank Account', artists: [{ name: '21 Savage' }], album: { name: 'Issa Album', images: [] } } },
        { track: { id: 'ghh50', name: 'Nonstop', artists: [{ name: 'Drake' }], album: { name: 'Scorpion', images: [] } } }
    ],
};